select P.PATIENT_ID,P.FIRST_NAME, P.LAST_NAME, C.CLAIM_ID,
C.SERVICE_DATE, C.PAYER, C.TOTAL_CHARGE, C.CLAIM_STATUS
FROM CLAIMS C JOIN PATIENTS P
ON C.PATIENT_ID = P.PATIENT_ID
WHERE CLAIM_STATUS='DENIED'
ORDER BY p.patient_id, c.claim_id;

SELECT PAYER, COUNT(CLAIM_ID) AS NUMBER_DNIED_CLAIMS, SUM(TOTAL_CHARGE) AS TOTAL_DENIED_AMOUNT
FROM CLAIMS
WHERE CLAIM_STATUS = 'DENIED'
GROUP BY PAYER
ORDER BY TOTAL_DENIED_AMOUNT DESC;
